# Generated by Django 4.2.7 on 2023-11-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petlisting',
            old_name='User',
            new_name='shelter',
        ),
    ]
