# Generated by Django 4.2.8 on 2023-12-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seeker_alter_shelter_location_delete_userprofile'),
        ('listings', '0002_rename_user_petlisting_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shelter'),
        ),
    ]
