# Generated by Django 4.2.8 on 2023-12-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='demo', max_length=255),
            preserve_default=False,
        ),
    ]
